### ISSUE TITLE
The question about  PyPDC program

### ISSUE THREAD

**Issue by haoyu112** [iicsys/pypmu#32]
When I run the main PyPDC program, it failed in the line 14 pdc.get(). 
![1631506833(1)](https://user-images.githubusercontent.com/90436214/133023534-b9da3cdd-3ce4-4b19-96ea-a992d5f2188b.jpg)
When I debug the program, I find that in pdc.py, we can run the line 102 self.get() successfully.
![image](https://user-images.githubusercontent.com/90436214/133023666-e5057b38-c736-4839-a465-cb8e20bb218a.png)
However, when I run the data = pdc.get() in main program, it failed in line 128 and 129 in Pdc.py.
![image](https://user-images.githubusercontent.com/90436214/133023975-0d37d1d4-0472-4a34-af0c-65ef7bfc0dca.png)
I am not sure whether the line 99 and 100 influence the result.
get_config = CommandFrame(self.pdc_id, version)
self.pmu_socket.sendall(get_config.convert2bytes())
Should I paste these commands in the main program? like this 
![image](https://user-images.githubusercontent.com/90436214/133023844-47786ed5-7c90-4618-af6d-8855cf4a8a97.png)

**Comment by sstevan** [comment]
Hey @haoyu112 

Let me explain what is actually happening:

First screenshot:
Line 9 - Aks PMU (or OpenPDC) to send ConfigFrame in order to describe the data stream that is about to be sent;
Line 11 - Send CommandFrame to start sending measurements;
Line 14 - Collect data stream until you get one formed and valid synchrophasor message;
