### ISSUE TITLE
TinyPDC cannot receive data from PMU of RTDS or Typhoon HIL

### ISSUE THREAD

**Issue by nlebang** [iicsys/pypmu#39]
Hi, I am trying TinyPDC with PMU simulated inside RTDS or Typhoon HIL. 
However, TinyPDC is stuck at 

`header = pdc.get_header()`
`2022-08-12 16:45:46,082 INFO [7] - Requesting header message from PMU (x.x.x.x:x)`

It cannot receive the header and config. I have tested my PMUs with PMU connection tester. They worked fine. But I cannot receive their data using TinyPDC.

**Comment by ddark008** [comment]
Can you dump some traffic with Wireshark?
What type of GTSYNC do you use?

**Comment by flome23** [comment]
Hello, 
I am facig the same issue and also haven´t found a solution yet.
So I am follwing this post.

**Comment by sstevan** [comment]
Hello everyone,

Have you tried removing the line `header = pdc.get_header()`? The same thing is happening for`pdc.get_config()`?

**Comment by flome23** [comment]
Hallo @sstevan ,
if run the tinyPDC program, the following error ocurs (see the first screenshot).

![Screenshot 2022-11-22 104903](https://user-images.githubusercontent.com/118541843/203282825-394604f7-e7be-46f6-b974-30faec57bbfc.png)

When I remove the lines, that you mentioned, then I this happens (see the second Screenshot).


![Screenshot 2022-11-22 104928](https://user-images.githubusercontent.com/118541843/203282839-0dde800c-6b3d-4572-9398-61e8a020c171.png)

What am I doing wrong?

Thank you very much!

**Comment by flome23** [comment]
Hey @nlebang ,

I had the same problem and while trying to find a solution, I realized, that the Typhoon HIL virtual PMUs use the TCP/IP IEEE C37.118-2005 protocol. The problem is, that the pypmu library can only communicate using the TCP/IP IEEE C37.118-2011 protocol. This little difference makes it impossible to recieve data from the virtual pmu. 
You can check it by yourself with the PMU connection tester tool. If you select the 2005-protocol, you will see the data from your virtual pmu. But if you select the 2011-protocol, you will get no data.

As far as I know, there is no Python library which works with the 2005 standard. 
If anyone has further information, please let me know, because I need to recieve the data from the PMU for my project.

Thanks

**Comment by ddark008** [comment]
> Hello everyone,
> 
> Have you tried removing the line `header = pdc.get_header()`? The same thing is happening for`pdc.get_config()`?

I check RTDS GTNET v1.0 with firmware 1.19 doesn't support HDR request and just drop connection
